spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/java-spring-rest
    username: postgres
    password: dago
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    validate-on-migrate: true